### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Ekrem",
  "sur_name": "Lale",
  "gender": "Male",
  "email": "ekrem@gmail.com",
  "address": "123 main street22",
  "date_of_birth": "2001-07-19",
  "registered_date": "2026-07-25"
}

###